### ISSUE TITLE
Support for bug 460945 and others

### ISSUE THREAD

**Issue by kysmith-csg** [eclipse-rap/org.eclipse.rap#204]
I am encountering https://bugs.eclipse.org/bugs/show_bug.cgi?id=460945 with View tabs:
![image](https://github.com/user-attachments/assets/c5a59ab0-c0f7-49fd-992d-67f25c86d8c5)

Related bugs:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=531450
https://bugs.eclipse.org/bugs/show_bug.cgi?id=533504
https://bugs.eclipse.org/bugs/show_bug.cgi?id=366151

You can see the text is cut off in the tab even though there should be plenty of space on the side. Refreshing the page or performing Reset Perspective causes the size to be correct.

One thing I noticed is that, on Refresh, the Close button is moved to the right, as if it was initially being drawn with too much right padding.

The font I am using is Montserrat 16pt normal. This is a custom font that is downloaded to the client via `org.eclipse.rap.rwt.client.service.ClientFileLoader.requireCss(String)`. I am defining the font in a custom theme stylesheet:

```css
CTabItem, TabItem {
    color: white;
    font: normal 16px 'Montserrat', sans-serif;
    background-color: #1774e5;
    background-image: none;
}
```

The other bugzilla tickets above show similar issues with things being cut off, like the layout is being calculated too "early".

Is there any known workaround for this? I don't want to manually reset the perspective since the user's settings would be gone, and asking the shell to redraw seems to do nothing on RAP.
